package com.anderscore;

public class Message {

    private static int autogenerated_id = 0;

    private int id = 0;

    private String content;

    public Message(String content) {
        this.content = content;
        id = autogenerated_id;
        autogenerated_id++;
    }

    public int getId() { return id; }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
